# Generated by Django 2.2.28 on 2022-12-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
