# Generated by Django 2.2.28 on 2022-12-03 21:37

from django.db import migrations
import main.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=main.fields.CommaSeparatedField(default='', max_length=2000),
        ),
    ]
